services:
  eventify-next:
    container_name: eventify-next
    restart: always
    image: node:24.11.1
    ports:
      - 4000:3000
    environment:
      - PORT=3000
    volumes:
      - ./:/usr/src/eventify-next
    working_dir: /usr/src/eventify-next

    networks:
      - client-network

    # FOR PRODUCTION
    command: bash -c "pnpm install && pnpm run build && pnpm run start"

networks:
  client-network:
    driver: bridge
